### PR TITLE
Review Belém-PA spider

### PR DESCRIPTION
**Pull request by rennerocha**
- Improve method to obtain number of items that exists in the period
  desired without relying on blocking requests
- Code formatting
- Add new field edition_number
- Filter gazettes scraped considering start_date argument

### CODE REVIEW

**Review by giuliocc — CHANGES_REQUESTED** [review]
The files that were downloaded here had something like this as content:

```
{"id":14103,"data_publicacao":"2020-10-20T03:00:00.000+0000","attr_stream_name":["dom_20-10-20.pdf"],"attr_stream_size":["416959"]}
```

Is there a missing step?

The previous steps and date filtering are working like a charm, though!

**Comment by rennerocha** [comment]
> The files that were downloaded here had something like this as content:
> 
> ```
> {"id":14103,"data_publicacao":"2020-10-20T03:00:00.000+0000","attr_stream_name":["dom_20-10-20.pdf"],"attr_stream_size":["416959"]}
> ```
> 
> Is there a missing step?
> 
> The previous steps and date filtering are working like a charm, though!

We need to add a header to the request, or else we will get this JSON content. I created a custom pipeline for this spider. This solves the problem.

**Comment by rennerocha** [comment]
@giuliocc I will change this spider again. It is more complicated than it should be. Wait for an update in the next days. :-)

**Comment by giuliocc** [comment]
> We need to add a header to the request, or else we will get this JSON content. I created a custom pipeline for this spider. This solves the problem.

Huum. Now the previous `DEFAULT_REQUEST_HEADERS` makes sense :) Do you prefer the pipeline implementation over the custom setting?

> @giuliocc I will change this spider again. It is more complicated than it should be. Wait for an update in the next days. :-)

Sure :+1: If my comment above doesn't make sense with what you discovered now just ignore it ;)

**Comment by rennerocha** [comment]
@giuliocc 

Creating a custom pipeline works, but the procedure to replace the existing file pipeline to the new one is a bit complicated (I didn't like to override the `update_settings` method). I think a more straightforward solution is to create a new custom property in the spider with the desired headers and update our custom file pipeline.

This is a more general solution and can be used by other spiders if needed.

**Review by giuliocc — APPROVED** [review]
That's nice :)

It has some overlap with #348 but I think this should be approved and we leave discussions about it for that PR.

**Pull request merged**
