### PR TITLE
Add spider for Nova Serrana, MG

### PR DESCRIPTION
**Pull request by pgarcias01**
Add spider for Nova Serrana, MG

### CODE REVIEW

**Comment by giuliocc** [comment]
Hey! Great to see you contributing again :)

I noticed the spider looks pretty similar to the one you submitted recently (Itauna). Maybe there's a pattern here for multiple cities similar to those two?

**Comment by pgarcias01** [comment]
> Hey! Great to see you contributing again :)
> 
> I noticed the spider looks pretty similar to the one you submitted recently (Itauna). Maybe there's a pattern here for multiple cities similar to those two?

Hi @giuliocc, we have other cities which are developed by the same company, being possible to use the same spyder. How do you suggest a way to add these cities?

**Comment by giuliocc** [comment]
I think that creating a parent spider class with most of the base code and child spider classes for each city is a good practice in this case. If they don't differ much, only a few changes are necessary for each child. Most spiders from SC (Santa Catarina) use this, you could take a look to get some inspiration :)

**Comment by rennerocha** [comment]
**question**: @pgarcias01 do you have a list of all cities that shares the same pattern?

**suggestion**: This spider is exactly equal to the one from Itauna-MG. Apparently there is no reason for code duplication, especially if we have more than two cities sharing the same pattern. Looking at the bottom of the pages it seems that they were developed by a company named Instar. You c ou

```
class BaseInstarSpider(BaseGazetteSpider):
    # Put your shared logic here
```

And then for each city you just create a subclass containing only the information required by that city:

```
class MgNovaSerranaSpider(BaseGazetteSpider):
    TERRITORY_ID = "3145208"
    name = "mg_novaserrana"
    allowed_domains = ["novaserrana.mg.gov.br"]
    start_urls = ["https://www.novaserrana.mg.gov.br/portal/diario-oficial/"]
```

**Comment by rennerocha** [comment]
**thought**: Instar has a list of city clients [here](https://www.instar.com.br/desenvolvimento-de-sites/orgaos-publicos/13/portfolio.html). Maybe we could create in another issue a list of all these cities and verify which of them can use this shared code.

**Comment by pgarcias01** [comment]
> **thought**: Instar has a list of city clients [here](https://www.instar.com.br/desenvolvimento-de-sites/orgaos-publicos/13/portfolio.html). Maybe we could create in another issue a list of all these cities and verify which of them can use this shared code.

Hi @rennerocha, I had already looked at this page, but not all of them use the diary page and there are other cities that are not there. I will close this PR and set up one with all that I found in the way they suggested.

**Comment by rennerocha** [comment]
@pgarcias01 there is no need to close this PR.
We don't need to do all the cities at once. I think that if you just create a base spider for Instar pages, and just Nova  Serrana spider inheriting from it, is enough to start. Then the other cities can be new PRs that will reuse this base spider.

**Pull request closed without merging**
