### PR TITLE
Added module with functions to get internal code from DiOE web site. 

### PR DESCRIPTION
**Pull request by adorilson**
This PR is part of #298

It add a new module has some utils function to retrieve data from DiOE web site (https://dosp.com.br/), which contain gazettes from several cities and entities.

These internal code will be need to do news spiders.

These functions are:
- filter_by (this is used by the others)
- get_states
- get_cities
- get_entities
- get_all_entities

Each function has your own doc string (and test, too).

### CODE REVIEW

**Comment by jvanz** [comment]
Do we already have a spider using this functions?

**Comment by adorilson** [comment]
> Do we already have a spider using this functions?

This functions are not to using in spiders itself.

They are utils to discovery the internal code that will be used in the spiders. Link the Itu SP spider (#303 ).

We do as follow:
```
>>> import dioe
>>> list(dioe.get_states())
[{'id': '0', 'name': 'Escolha o Estado'}, {'id': '11', 'name': 'Minas
 Gerais (MG)'}, {'id': '16', 'name': 'Pernambuco (PE)'}, {'id': '23',
 'name': 'Rio Grande do Sul (RS)'}, {'id': '26', 'name': 'São Paulo (
SP)'}, {'id': '28', 'name': 'Modelândia (MO)'}]
>>> for city in dioe.get_cities(26):
...     if 'Itu' in city['name']:
...         print(city)
...         
...     
... 
{'id': '4923', 'name': 'Itu'}
{'id': '4924', 'name': 'Itupeva'}
{'id': '5511', 'name': 'Itupeva Legislativo'}
``` 

Now, we know the codes from Itu, Itupeva and Itupeva Legistativo and we can build theses spiders.

**Comment by jvanz** [comment]
I would say we can have documentation about it instead of a module just to get this info. I'm not sure if a is worth.

**Comment by rennerocha** [comment]
Closed as stale.

**Pull request closed without merging**
