### PR TITLE
Organize base spiders

### PR DESCRIPTION
**Pull request by rennerocha**
This idea was discussed during Python Brasil sprint. We have the base spiders spread in the structure of the project. Most of them were located in `base.py` , but we had other in a separated file `instar_base.py`. It is possible that we will have other cities that uses a common system that can be extracted as a base spider.

This PR wants to organize this to make it easier (and clearer) for a contributor where to place their new base spider (and related classes/functions).

### CODE REVIEW

**Review by giuliocc — APPROVED** [review]
Great job! Everything seems to be working :) LGTM

**Comment by giuliocc** [comment]
#347 was merged and it has a base spider :/

Could you add that one too?

**Review by jvanz — APPROVED** [review]

**Comment by jvanz** [comment]
> #347 was merged and it has a base spider :/
> 
> Could you add that one too?

Yeah, I think the branch needs to be rebased in the latest main and fix the missing base spider. ;)

**Review by jvanz — CHANGES_REQUESTED** [review]
Marking as `Request changes` just to signal that we need to fix latest base spider.

**Pull request merged**
