### PR TITLE
Add all cities

### PR DESCRIPTION
**Pull request by alexandrevicenzi**

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
The idea here is to add all cities so people can know what is implemented or not, this may be a good start if someone wants to help. The previous list was a bit outdated and had some issues.

Let me know if it would be nice to add more information to the table.

**Comment by ejulio** [comment]
Awesome!
I'd just push the script you probably used to create it so people won't need to update it manually.

**Comment by alexandrevicenzi** [comment]
@ejulio where it would fit (path)? the script is also a mess, so I need to work properly on it.

**Review by ejulio — COMMENTED** [review]
For me, this PR is good to go.
Not sure about the path for the script and it can be added in a new PR if that makes sense.
Though, I think it wouldn't be a problem to add it here..

@rennerocha thoughts on it?

**Review by jvanz — CHANGES_REQUESTED** [review]
I think the script can live in some directory like `devel` or `scripts`. Furthermore, add a target in the Makefile. Thus, the user does not need to know how to call the script . Something like `make update_cities`.

Please, rebase your branch. There is some conflict with the latest changes on main. Thanks!

**Comment by alexandrevicenzi** [comment]
I'll rebase and add the script + command on makefile.

**Comment by giuliocc** [comment]
I think this idea is great :) Nice work!

**Comment by anapaulagomes** [comment]
You have also the option of adding the script as a scheduled script on Github Actions, so it would run and update the list daily, for instance.

**Comment by jvanz** [comment]
> You have also the option of adding the script as a scheduled script on Github Actions, so it would run and update the list daily, for instance.

That's interesting idea! We could run this when we got a pull request merged.

**Comment by rennerocha** [comment]
Keeping cities manually updated is not scaling. Probably we will use a database to store this information and deprecate CITIES.md file in future.

**Pull request closed without merging**
