### PR TITLE
Spider for Vila Velha/ES

### LINKED ISSUE #319: Add spider for Vila Velha/ES
There is a city of Vila Velha with a green tick on CITIES.md but the spider for `es_associacao_de_municipios` does not include Vila Velha, as far as I could see (the second page of this gazette has the list of cities included and Vila Velha is not there). So I will create a specific spider for Vila Velha.

Their gazette repository is at https://www.vilavelha.es.gov.br/diariooficial/ConsultaDiario.aspx.

### PR DESCRIPTION
**Pull request by rodbv**
Closes #319 

This PR replaces #318 which will be closed,  due to the several changes on the project structure.

Code to support `file_requests` in the pipeline was provided by @giuliocc 👏

### CODE REVIEW

**Review by giuliocc — APPROVED** [review]

**Comment by giuliocc** [comment]
@jvanz, since I proposed the pipeline changes I felt like I wasn't the appropriate reviewer and it needed a look from another person. I asked it to @rennerocha yesterday but I forgot to request it here. Sorry ;)

**Comment by giuliocc** [comment]
@rodbv sorry for the long wait time for this. I've made some changes to resolve conflicts and some minor stuff regarding style and what appears to be a new `dataFinal` field in the starting request.

I'm approving this PR, let me know your thoughts if possible and again: apologies!

**Comment by giuliocc** [comment]
@jvanz @rennerocha I'm planning on squashing and merging this PR in the next few days. Let me know if anything needs to change

**Comment by giuliocc** [comment]
Thank you so much for the contribution @rodbv !

Hope the wait didn't discourage you from contributing again :/ The maintaining team is not so active since then because of the project's plataform MVP launch and other life stuff.

**Comment by rodbv** [comment]
Hey Giulio thanks for the merge and the message. I was assuming the delay was due to work/life overload, especially in pandemic times...thanks a lot! I'll see if there any other issues I can pull, if there's any specific issue you or the team needs help with, I'm glad to help. Cheers!

**Comment by giuliocc** [comment]
Thanks for being so understanding. Really appreciate it :)

Right now I won't be adding much stuff to this repo. Here I'll focus on slowly but surely reviewing the pending PRs. If you want to tackle some issues, the current milestone is refactoring the existing capital cities spiders to make them _production ready_.

What do I mean by _production ready_? Being able to filter by the `start_date` argument, not making unnecessary requests when filtering by today's or yesterday's date.

Outside of that, finishing the stale PRs for capital cities spiders, adding spiders for cities above 100k population or any other spider or project improvement is always welcome :)

**Pull request merged**
