### PR TITLE
Remove Docker dependency for development

### PR DESCRIPTION
**Pull request by rennerocha**
After removing text extraction (https://github.com/okfn-brasil/querido-diario/pull/310) and database dependency (https://github.com/okfn-brasil/querido-diario/commit/0447f2b2f4e342346c50bbe4a0c0abd512584ce8) from the project, requiring Docker to install and use the project seems to be a barrier for new developers, especially considering that we are not using anything that really requires a Docker container to be running in developers machine.

In my opinion, a good old virtualenv, that can be created using built-in `[venv](https://docs.python.org/3/library/venv.html)` module is enough to create a development environment suitable for the majority of developers.

On this PR I am suggesting to remove any reference to Docker to make developers life easier.

When (and if) we need to deploy this project in another environment on production, we can chose if Docker is the best solution, but these configurations can be separated and not affecting people that only wants to contribute with the spiders.

### CODE REVIEW

**Comment by rodbv** [comment]
This would also close issue #320 which I opened yesterday, to add `venv` instructions on README.md

**Comment by jeanmask** [comment]
I agree, decouple database and text extraction pipelines can be a good idea to help new interested collaborators.

**Comment by giuliocc** [comment]
I think it does make sense to remove it. Not sure if we will ever go back to using it, but if we do it shouldn't be a problem anyways.

If I may suggest a few things:
- Move the `data_processing` directory to the project root
- Create a `requirements` folder with `requirements.[in,txt]` and `dev.[in,txt]`
- Change `Makefile` to reflect commands that usually were made using Docker

**Review by jvanz — APPROVED** [review]

**Comment by rennerocha** [comment]
Replaced in favor of https://github.com/okfn-brasil/querido-diario/pull/341 (that solves some weird conflicts).

**Pull request closed without merging**
