### PR TITLE
Add Ribeirão Preto spider

### PR DESCRIPTION
**Pull request by samuelgrigolato**
Please check the code comments inside the commits and #31 for further info.

Worth noting that I needed to add a custom file download item pipeline similar to what @rennerocha suggested in #10. Please take a special look in this class while reviewing as it impacts every crawler (I tried to keep the default behavior though).

### CODE REVIEW

**Comment by rennerocha** [comment]
I don't like the idea of using a special custom pipeline that is useful only for one spider in a way that would affect all spiders. In this case, I think to use this pipeline only for this spider is a better idea.

I did something similar in Salvador spider:
https://github.com/okfn-brasil/diario-oficial/pull/47/files#diff-7f4e787e93394a5014afdd591305acb3R21

Anyway, your pipeline seems to be something that could be used in other spiders one day, so I would rename it from `CustomFilesPipeline` to something more explanatory (as `SessionBasedFilesPipeline`, or something better because I think my idea was terrible) and leave it in the pipelines module to be easier to use it in other spiders.

**Comment by samuelgrigolato** [comment]
> Anyway, your pipeline seems to be something that could be used in other spiders one day

Exactly, when designing this item pipeline I was trying to achieve a generic one, not one specific for Ribeirão Preto. The `cookiejar` + `formdata` solution probably apply to a lot of cases so it may help others, and can be further improved if needed, e.g to add headers support, without breaking compatibility with existing crawlers.

Regarding the name of the pipeline I'll try to improve it and update this PR, any suggestions would be greatly appreciated.

**Comment by jaswdr** [comment]
@samuelgrigolato any plans to continue this PR?

**Comment by samuelgrigolato** [comment]
Hi @jaswdr. Sometime after my last comment I decided to stop working on this and missed the opportunity and timing to properly comment and let you guys know, sorry about that. I'm still not able to resume working on this but I'm here to answer any questions one my have about the code.

**Comment by rennerocha** [comment]
Closing stale PR.

**Pull request closed without merging**
